type Director {
  id: BigInteger
  name: String
}

type Favourites {
  movie: Movie
  user_id: BigInteger
}

type Movie {
  director: Director
  id: BigInteger
  name: String
  year: String
}

"Query root"
type Query {
  "Get Favourites movies"
  getFavouriteMovies(userId: BigInteger): [Favourites]
}

"Scalar for BigDecimal"
scalar BigDecimal

"Scalar for BigInteger"
scalar BigInteger
