---
openapi: 3.0.3
info:
  title: qgql API
  version: 1.0.0-SNAPSHOT
paths:
  /todo:
    get:
      tags:
      - Todo Rest Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoList'
    post:
      tags:
      - Todo Rest Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
components:
  schemas:
    TodoItem:
      type: object
      properties:
        id:
          format: int64
          type: integer
        headline:
          type: string
        body:
          type: string
        todoList:
          $ref: '#/components/schemas/TodoList'
    TodoList:
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/TodoItem'
